### ISSUE TITLE
danger 3

### ISSUE THREAD

**Issue by valeriomazzeo** [nakiostudio/danger-xcov#11]
Could you please update the gem spec to support danger 3.x.x ?

At the moment when Danger 3 is specified in the gem file an old version of danger-xcov is installed (0.1.2)

Thank you

**Comment by nakiostudio** [comment]
Hi @valeriomazzeo 👋 

Once again, thanks for reporting :)

**Comment by valeriomazzeo** [comment]
thank you again for fixing it :)
