### ISSUE TITLE
Is it need maintain xcov_report folder

### ISSUE THREAD

**Issue by RafaelPlantard** [nakiostudio/danger-xcov#13]
How danger-xcov get generated xcov data?

**Comment by nakiostudio** [comment]
Hi @RafaelPlantard 👋 

Not really sure what's the question. Are you asking whether is required to keep the `xcov_report` folder in order to get the `danger-xcov` report?

**Comment by RafaelPlantard** [comment]
Forgot about my question, my mistake.

**Comment by nakiostudio** [comment]
No problem 👍

**Comment by RafaelPlantard** [comment]
Thanks @nakiostudio
