### ISSUE TITLE
Impossible to use with Danger 2.1.1

### ISSUE THREAD

**Issue by valeriomazzeo** [nakiostudio/danger-xcov#9]
I guess the gem dependency needs to be updated, it doesn't look like there are breaking changes on danger though from 2.0 to 2.1

```
Bundler could not find compatible versions for gem "danger":
  In Gemfile:
    danger (= 2.1.1)

    danger-xcov (= 0.2.0) was resolved to 0.2.0, which depends on
      danger (~> 2.0.0)
```

**Comment by nakiostudio** [comment]
Hi @valeriomazzeo 👋 

Thanks for reporting, let me dig a bit more as `~> 2.0.0` means 2.0.0 and above therefore it shouldn't break.

**Comment by valeriomazzeo** [comment]
@nakiostudio I don't think that means that includes minor versions (as they might include breaking changes).

I changed it to `~> 2.1` for my plugins and everything works cause different versions can be loaded correctly.

Anyway, I am interested in the solution if what you said it's true 👍

**Comment by nakiostudio** [comment]
Hi again, I've just pushed `0.2.1` fixing the issue. Really strange, as you said doesn't seem to be any breaking change between 2.0.x and 2.1.x 🤔

Thanks for the heads up 👍

**Comment by valeriomazzeo** [comment]
np 👍
